### ISSUE TITLE
malloc(): smallbin double linked list corrupted

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#271]
game suddenly crashes. Gui disappears, no pause, just back to the console

malloc(): smallbin double linked list corrupted

pvp game using map Athena's valley.

![image](https://user-images.githubusercontent.com/16764864/46556560-a4d2ab00-c8ac-11e8-84dc-d7a9d1933e47.png)

```
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
*ERROR* [2018-10-05 13:59:50] In [model.cpp::loadMeshTexture Line: 738] Error v4 model is missing texture [/home/andy/src/zg-local/zetaglest-data/techs/zetapack/factions/japanese/units/taketaba_gunner/../castle/models/muzzleflash.tga] textureFlags = 1 meshIndex = 10 textureIndex = 0 modelFile [/home/andy/src/zg-local/zetaglest-data/techs/zetapack/factions/japanese/units/taketaba_gunner/../castle/models/taketaba_teppo_death.g3d]
*ERROR* [2018-10-05 13:59:50] In [model.cpp::loadMeshTexture Line: 738] Error v4 model is missing texture [/home/andy/src/zg-local/zetaglest-data/techs/zetapack/factions/japanese/units/teppo_ashigaru/../castle/models/muzzleflash.tga] textureFlags = 1 meshIndex = 0 textureIndex = 0 modelFile [/home/andy/src/zg-local/zetaglest-data/techs/zetapack/factions/japanese/units/teppo_ashigaru/../castle/models/arquebuseridle.g3d]
*ERROR* [2018-10-05 13:59:50] In [model.cpp::loadMeshTexture Line: 738] Error v4 model is missing texture [/home/andy/src/zg-local/zetaglest-data/techs/zetapack/factions/japanese/units/teppo_ashigaru/../castle/models/muzzleflash.tga] textureFlags = 1 meshIndex = 0 textureIndex = 0 modelFile [/home/andy/src/zg-local/zetaglest-data/techs/zetapack/factions/japanese/units/teppo_ashigaru/../castle/models/arquebusermove.g3d]
*ERROR* [2018-10-05 13:59:50] In [model.cpp::loadMeshTexture Line: 738] Error v4 model is missing texture [/home/andy/src/zg-local/zetaglest-data/techs/zetapack/factions/japanese/units/teppo_ashigaru/../castle/models/muzzleflash.tga] textureFlags = 1 meshIndex = 0 textureIndex = 0 modelFile [/home/andy/src/zg-local/zetaglest-data/techs/zetapack/factions/japanese/units/teppo_ashigaru/../castle/models/arquebusermove.g3d]
*ERROR* [2018-10-05 13:59:50] In [model.cpp::loadMeshTexture Line: 738] Error v4 model is missing texture [/home/andy/src/zg-local/zetaglest-data/techs/zetapack/factions/japanese/units/teppo_ashigaru/../castle/models/muzzleflash.tga] textureFlags = 1 meshIndex = 1 textureIndex = 0 modelFile [/home/andy/src/zg-local/zetaglest-data/techs/zetapack/factions/japanese/units/teppo_ashigaru/../castle/models/taketaba_teppo_morph.g3d]
*ERROR* [2018-10-05 13:59:50] In [model.cpp::loadMeshTexture Line: 738] Error v4 model is missing texture [/home/andy/src/zg-local/zetaglest-data/techs/zetapack/factions/japanese/units/teppo_ashigaru/../castle/models/muzzleflash.tga] textureFlags = 1 meshIndex = 0 textureIndex = 0 modelFile [/home/andy/src/zg-local/zetaglest-data/techs/zetapack/factions/japanese/units/teppo_ashigaru/../castle/models/arquebuser_deathb.g3d]
*ERROR* [2018-10-05 13:59:50] In [model.cpp::loadMeshTexture Line: 738] Error v4 model is missing texture [/home/andy/src/zg-local/zetaglest-data/techs/zetapack/factions/japanese/units/teppo_ashigaru/../castle/models/muzzleflash.tga] textureFlags = 1 meshIndex = 0 textureIndex = 0 modelFile [/home/andy/src/zg-local/zetaglest-data/techs/zetapack/factions/japanese/units/teppo_ashigaru/../castle/models/arquebuserdeath.g3d]
*ERROR* [2018-10-05 13:59:50] In [model.cpp::loadMeshTexture Line: 738] Error v4 model is missing texture [/home/andy/src/zg-local/zetaglest-data/techs/zetapack/factions/japanese/units/teppo_ashigaru/../castle/models/muzzleflash.tga] textureFlags = 1 meshIndex = 0 textureIndex = 0 modelFile [/home/andy/src/zg-local/zetaglest-data/techs/zetapack/factions/japanese/units/teppo_ashigaru/../castle/models/arquebuserb_deathc.g3d]
Game unique identifier is: 1250500a-c8ce-11e8-8e72-cd2516571e6c
Auto Change resolution to (1920 x 1080) from (1024 x 768)
malloc(): smallbin double linked list corrupted
Aborted
```

**Comment by andy5995** [comment]
seems like it may not have anything to do with a linked list. The fellow reported the same error message but not using a linked list, just strcat()

https://stackoverflow.com/questions/33831123/malloc-smallbin-double-linked-list-corrupted

**Comment by mathusummut** [comment]
This issue is being addressed. @Jammyjamjamman had this stacktrace:

`Thread 35 "zetaglest" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff7cff9700 (LWP 25541)]
0x0000000000548029 in std::_Construct<Game::NetworkCommand, Game::NetworkCommand> (__p=<optimised out>)
    at /usr/include/c++/7/bits/stl_uninitialized.h:82
82                    for (; __first != __last; ++__first, (void)++__cur)
(gdb) u
Game::handleSIGSEGV (sig=11)
    at /home/<user>/git_repos/zetaglest/zetaglest-source-fork/source/glest_game/main/main.cpp:8165
8165                    handleSIGSEGV(int sig) {
(gdb) u
8167                            szBuf[8096] = "";
(gdb) u
8165                    handleSIGSEGV(int sig) {
(gdb) u
8167                            szBuf[8096] = "";
(gdb) u
8168                    snprintf(szBuf, 8096,
(gdb) u
8165                    handleSIGSEGV(int sig) {
(gdb) u
8168                    snprintf(szBuf, 8096,
(gdb) u
8165                    handleSIGSEGV(int sig) {
(gdb) u
8167                            szBuf[8096] = "";
(gdb) u
8168                    snprintf(szBuf, 8096,
(gdb) u 10
In [/home/<user>/git_repos/zetaglest/zetaglest-source-fork/source/glest_game/main/main.cpp::handleSIGSEGV Line: 8170] Error detected: signal 11:
Error saved to logfile [/home/<user>/.zetaglest/error.log]
*ERROR* [2019-01-27 21:38:08] In [/home/<user>/git_repos/zetaglest/zetaglest-source-fork/source/glest_game/main/main.cpp::handleRuntimeError Line: 851] [In [/home/<user>/git_repos/zetaglest/zetaglest-source-fork/source/glest_game/main/main.cpp::handleSIGSEGV Line: 8170] Error detected: signal 11:
] gameInitialized = 1, program = 0x14fb490
*ERROR* [2019-01-27 21:38:08] In [program.cpp::loopWorker 768] ERROR / WARNING soundThreadManager->isThreadExecutionLagging is TRUE
Restarting audio source because of buffer underrun.
Restarting audio source because of buffer underrun.
*ERROR* [2019-01-27 21:38:09] In [/home/<user>/git_repos/zetaglest/zetaglest-source-fork/source/glest_game/main/main.cpp::handleRuntimeError Line: 881] [In [/home/<user>/git_repos/zetaglest/zetaglest-source-fork/source/glest_game/main/main.cpp::handleSIGSEGV Line: 8170] Error detected: signal 11:

Stack Trace:
/home/<user>/git_repos/zetaglest/zetaglest-source-fork/mk/linux/build/zetaglest:Game::ExceptionHandler::handleRuntimeError(char const*, bool)address [0x6916f2] line: 1203
/home/<user>/git_repos/zetaglest/zetaglest-source-fork/mk/linux/build/zetaglest:Game::handleSIGSEGV(int)address [0x691bc6] line: 8175
/lib/x86_64-linux-gnu/libc.so.6:()address [0x7ffff4e41f20] line: 0
/home/<user>/git_repos/zetaglest/zetaglest-source-fork/mk/linux/build/zetaglest:void std::vector<Game::NetworkCommand, std::allocator<Game::NetworkCommand> >::_M_realloc_insert<Game::NetworkCommand const&>(__gnu_cxx::__normal_iterator<Game::NetworkCommand*, std::vector<Game::NetworkCommand, std::allocator<Game::NetworkCommand> > >, Game::NetworkCommand const&)address [0x548029] line: 82
/home/<user>/git_repos/zetaglest/zetaglest-source-fork/mk/linux/build/zetaglest:Game::GameNetworkInterface::requestCommand(Game::NetworkCommand const*, bool)address [0x8492b7] line: 948
/home/<user>/git_repos/zetaglest/zetaglest-source-fork/mk/linux/build/zetaglest:Game::Commander::pushNetworkCommand[abi:cxx11](Game::NetworkCommand const*, bool) constaddress [0x53db7b] line: 689
/home/<user>/git_repos/zetaglest/zetaglest-source-fork/mk/linux/build/zetaglest:Game::Commander::tryGiveCommand[abi:cxx11](Game::Unit const*, Game::CommandType const*, Shared::Graphics::Vec2<int> const&, Game::UnitType const*, Game::CardinalDir, bool, Game::Unit*, int) constaddress [0x53eb69] line: 211
/home/<user>/git_repos/zetaglest/zetaglest-source-fork/mk/linux/build/zetaglest:Game::AiInterface::giveCommand[abi:cxx11](int, Game::CommandType const*, Shared::Graphics::Vec2<int> const&, int)address [0x4f2bbe] line: 211
/home/<user>/git_repos/zetaglest/zetaglest-source-fork/mk/linux/build/zetaglest:Game::Ai::harvest(int)address [0x4e41b1] line: 211
/home/<user>/git_repos/zetaglest/zetaglest-source-fork/mk/linux/build/zetaglest:Game::Ai::update()address [0x4e8d36] line: 628
/home/<user>/git_repos/zetaglest/zetaglest-source-fork/mk/linux/build/zetaglest:Game::AiInterfaceThread::execute()address [0x4f0193] line: 300
/home/<user>/git_repos/zetaglest/zetaglest-source-fork/mk/linux/build/zetaglest:Shared::Platform::Thread::beginExecution(void*)address [0xa9d438] line: 237
/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0:()address [0x7ffff7b0ccbc] line: 0
/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0:()address [0x7ffff7b80d69] line: 0
/lib/x86_64-linux-gnu/libpthread.so.0:()address [0x7ffff788d6db] line: 0
/lib/x86_64-linux-gnu/libc.so.6:clone()address [0x7ffff4f2488f] line: 0
]
zetaglest: malloc.c:2401: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

Thread 35 "zetaglest" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff4e43801 in __GI_abort () at abort.c:79
#2  0x00007ffff4e96a91 in __malloc_assert (file=<optimised out>, function=<optimised out>, line=<optimised out>, 
    assertion=<optimised out>) at malloc.c:298
#3  sysmalloc (nb=nb@entry=224, av=av@entry=0x7fff5c000020) at malloc.c:2398
#4  0x00007ffff4e97ff0 in _int_malloc (av=av@entry=0x7fff5c000020, bytes=bytes@entry=208) at malloc.c:4125
#5  0x00007ffff4e9a2ed in __GI___libc_malloc (bytes=208) at malloc.c:3065
#6  0x00007ffff64a0b2f in _XEnq () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#7  0x00007ffff649d87f in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#8  0x00007ffff649e1c5 in _XEventsQueued () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#9  0x00007ffff647f74a in XFlush () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#10 0x00007ffff7b6a322 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#11 0x00007ffff7ada147 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#12 0x00007ffff7ada195 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#13 0x0000000000aa45e0 in Shared::Platform::Window::handleEvent ()
    at /home/<user>/git_repos/zetaglest/zetaglest-source-fork/source/shared_lib/sources/platform/sdl/window.cpp:217
#14 0x0000000000691909 in Game::ExceptionHandler::handleRuntimeError (
    msg=msg@entry=0x7fff7cfede00 "In [/home/<user>/git_repos/zetaglest/zetaglest-source-fork/source/glest_game/main/main.cpp::handleSIGSEGV Line: 8170] Error detected: signal 11:\n", getStackTraceString=getStackTraceString@entry=true)
    at /home/<user>/git_repos/zetaglest/zetaglest-source-fork/source/glest_game/main/main.cpp:909
#15 0x0000000000691bc6 in Game::handleSIGSEGV (sig=<optimised out>)
    at /home/<user>/git_repos/zetaglest/zetaglest-source-fork/source/glest_game/main/main.cpp:8174
#16 <signal handler called>
#17 0x0000000000548029 in std::_Construct<Game::NetworkCommand, Game::NetworkCommand> (__p=<optimised out>)
    at /usr/include/c++/7/bits/stl_uninitialized.h:82
#18 std::__uninitialized_copy<false>::__uninit_copy<std::move_iterator<Game::NetworkCommand*>, Game::NetworkCommand*>
    (__result=<optimised out>, __last=..., __first=...) at /usr/include/c++/7/bits/stl_uninitialized.h:83
#19 std::uninitialized_copy<std::move_iterator<Game::NetworkCommand*>, Game::NetworkCommand*> (
    __result=<optimised out>, __last=..., __first=...) at /usr/include/c++/7/bits/stl_uninitialized.h:134
#20 std::__uninitialized_copy_a<std::move_iterator<Game::NetworkCommand*>, Game::NetworkCommand*, Game::NetworkCommand>---Type <return> to continue, or q <return> to quit---
 (__result=<optimised out>, __last=..., __first=...) at /usr/include/c++/7/bits/stl_uninitialized.h:289
#21 std::__uninitialized_move_if_noexcept_a<Game::NetworkCommand*, Game::NetworkCommand*, std::allocator<Game::NetworkCommand> > (__alloc=..., __result=<optimised out>, __last=0x7fff50001180, __first=0x7fff580011e0)
    at /usr/include/c++/7/bits/stl_uninitialized.h:312
#22 std::vector<Game::NetworkCommand, std::allocator<Game::NetworkCommand> >::_M_realloc_insert<Game::NetworkCommand const&> (this=this@entry=0x152c678, __position=
  {networkCommandType = 0, unitId = 0, unitTypeId = 0, commandTypeId = 85, positionX = 0, positionY = 0, targetId = 0, wantQueue = 0 '\000', fromFactionIndex = 0 '\000', unitFactionUnitCount = 0, unitFactionIndex = 0 '\000', commandStateType = 0 '\000', commandStateValue = 875573296, unitCommandGroupId = 1931488544}, __args#0=...)
    at /usr/include/c++/7/bits/vector.tcc:424
#23 0x00000000008492b7 in std::vector<Game::NetworkCommand, std::allocator<Game::NetworkCommand> >::push_back (
    __x=..., this=0x152c678) at /usr/include/c++/7/bits/stl_vector.h:948
#24 Game::GameNetworkInterface::requestCommand (this=this@entry=0x152bd00, 
    networkCommand=networkCommand@entry=0x7fff7cff2700, insertAtStart=insertAtStart@entry=false)
    at /home/<user>/git_repos/zetaglest/zetaglest-source-fork/source/glest_game/network/network_interface.cpp:415
#25 0x000000000053db7b in Game::Commander::pushNetworkCommand[abi:cxx11](Game::NetworkCommand const*, bool) const (
    this=0x98804f0, networkCommand=networkCommand@entry=0x7fff7cff2700, insertAtStart=insertAtStart@entry=false)
    at /home/<user>/git_repos/zetaglest/zetaglest-source-fork/source/glest_game/game/commander.cpp:685
#26 0x000000000053eb69 in Game::Commander::tryGiveCommand[abi:cxx11](Game::Unit const*, Game::CommandType const*, Shared::Graphics::Vec2<int> const&, Game::UnitType const*, Game::CardinalDir, bool, Game::Unit*, int) const (
    this=<optimised out>, unit=<optimised out>, commandType=commandType@entry=0x2ec77480, pos=..., 
    unitType=<optimised out>, facing=..., tryQueue=false, targetUnit=0x0, unitGroupCommandId=-1)
    at /home/<user>/git_repos/zetaglest/zetaglest-source-fork/source/glest_game/game/commander.cpp:260
#27 0x00000000004f2bbe in Game::AiInterface::giveCommand[abi:cxx11](int, Game::CommandType const*, Shared::Graphics::Vec2<int> const&, int) (this=0x1c71a6c0, unitIndex=unitIndex@entry=4, commandType=commandType@entry=0x2ec77480, 
    pos=..., unitGroupCommandId=unitGroupCommandId@entry=-1)
    at /home/<user>/git_repos/zetaglest/zetaglest-source-fork/source/glest_game/ai/ai_interface.cpp:690
#28 0x00000000004e41b1 in Game::Ai::harvest (this=0x1c71a6e0, unitIndex=4)
    at /home/<user>/git_repos/zetaglest/zetaglest-source-fork/source/glest_game/ai/ai.cpp:1498
#29 0x00000000004e8d36 in Game::Ai::update (this=<optimised out>)`
